---
- name: Alterando hostname
  hostname: name={{ new_hostname }}

- name: Alterando /etc/hosts
  lineinfile:
    dest: "/etc/hosts"
    regexp: "^{{ hostvars[item].ansible_default_ipv4.address }}"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ new_hostname }}"
  with_items: groups['php_server']
